### ISSUE TITLE
Support Joi `abortEarly` and other validation options

### ISSUE THREAD

**Issue by kosiakMD** [twiddler/envjoi#2]
Could you provide the support of Joi validation options (`ValidationOptions` as `BaseValidationOptions` on Joi library) to support `abortEarly` which gives ability to do not show only the first wrong/missed env variable?

**Comment by twiddler** [comment]
Thanks for your request. I had a quick look into it and I think this should be doable. However no elegant solution crossed my mind immediately. I am currently busy with another project, so I won't work on `envjoi` for some weeks except updating dependencies. Feel free to open a pull request if you already have a solution in mind! :v:

**Comment by twiddler** [comment]
I have stopped maintaining this project. See the README.
